config/routes.rb
Rails.application.routes.draw do
  root 'trades#index'

  get '/accounts/balance', to: 'accounts#balance'
  post '/transfer_money', to: 'transfer_money#create'

  resources :trades, only: :index
end

app/models/account.rb
# Class to model Account
class Account < ApplicationRecord
  has_many :traders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trade.rb
# Model to save all trades from application
class Trade < ApplicationRecord
  belongs_to :account

  validates :account_id, :amount, presence: true
  validates :amount, numericality: true
end

app/controllers/accounts_controller.rb
# Controller to Account
class AccountsController < ApplicationController
  def balance
    account_id = params[:account_id]

    @balance = AccountService.new(account_id).balance

    return unless @balance == false

    flash[:error] = t('accounts.balance.not_exist')
    redirect_to trades_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trades_controller.rb
# Controller to trades
class TradesController < ApplicationController
  def index
    @traders = Trade.order(created_at: :desc)
  end
end

app/controllers/transfer_money_controller.rb
# Controller to transfer money
class TransferMoneyController < ApplicationController
  def new; end

  def create
    service = TransferMoneyService.new(params[:source_account_id],
                                       params[:destination_account_id],
                                       params[:amount])

    if service.transfer
      flash[:notice] = t('transfer_money.success')
    else
      flash[:error] = t('transfer_money.error')
    end

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'   # Green
    when 'error'
      'alert-danger'    # Red
    when 'alert'
      'alert-warning'   # Yellow
    when 'notice'
      'alert-info'      # Blue
    else
      flash_type.to_s
    end
  end
end

app/views/accounts/balance.html.erb
<h2><%= t('.account', account_id: params[:account_id]) %></h2>
<h3><%= t('.title') %> <small><%= number_to_currency(@balance) %></small></h3>

<%= link_to t('actions.back'), root_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Fake Bank', root_path, class: 'navbar-brand' %>
        </div>
      </div>
    </nav>

    <%= render partial: 'shared/flash_messages', flash: flash %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= message %>
  </div>
<% end %>

app/views/trades/index.html.erb
<div class="row">
  <h4><%= t('.get_balance') %></h4>

  <%= form_tag accounts_balance_path, method: :get,
               id: 'get_balance', class: 'form-inline' do %>
    <div class="form-group">
      <%= label_tag :account_id, t('.account') %>
      <%= text_field_tag :account_id, params[:account_id],
                         class: 'form-control' %>
    </div>

    <%= submit_tag t('.get_balance'), class: 'btn btn-primary' %>
  <% end %>
</div>

<div class="row">
  <h4><%= t('.transfer') %></h4>

  <%= form_tag transfer_money_path, method: 'POST',
               id: 'transfer_money', class: 'form-inline' do %>
    <div class="form-group">
      <%= label_tag :source_account_id, t('.source_account_id') %>
      <%= text_field_tag :source_account_id, params[:source_account_id],
                         class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag :destination_account_id, t('.destination_account_id') %>
      <%= text_field_tag :destination_account_id, params[:destination_account_id],
                         class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag :amount, t('.amount') %>
      <%= text_field_tag :amount, params[:amount], class: 'form-control' %>
    </div>

    <%= submit_tag t('.transfer'), class: 'btn btn-primary' %>
  <% end %>
</div>

<hr/>

<h3><%= t('.title') %></h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="col-md-4"><%= t('.created_at') %></th>
      <th class="col-md-4"><%= t('.account_id') %></th>
      <th class="col-md-4"><%= t('.amount') %></th>
    </tr>
  </thead>
  <tbody>
    <% @traders.each do |trade| %>
      <tr>
        <td class="col-md-4">
          <%= I18n.l(trade.created_at, format: :short) %>
        </td>
        <td class="col-md-4">
          <%= trade.account_id %>
        </td>
        <td class="col-md-4">
          <%= number_to_currency(trade.amount) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>